version: '3.8'

services:

  web:
    build:
      context: ./..
      dockerfile: ./deployment/Dockerfile
    ports:
      - 9000:9000
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - ./..:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://deployment-redis-1:6379
      - CELERY_RESULT_BACKEND=redis://deployment-redis-1:6379
    depends_on:
      - redis
  
  worker:
    build:
      context: ./..
      dockerfile: ./deployment/Dockerfile
    command: python worker.py
    volumes:
      - ./..:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://deployment-redis-1:6379
      - CELERY_RESULT_BACKEND=redis://deployment-redis-1:6379
      - C_FORCE_ROOT=true
    depends_on:
      - web
      - redis
  
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    